import keyboard

# TODO:
# 1. 处理多模态输出(图片、语言)

global paused

def termintate_llm_output():
    global paused
    paused = True
    

def process_response(response,show_reasoning=True,hotkey:str='q',sep:str="#"*30):
    """handling streaming response generated by the openAIChatCompletement,user can press 'key' to terminate the output from LLM    

    Args:
        response : response returned by the llm.ask_LLM()
        hotkey: must be in format like "ctrl+alt+p".the key user pressed to stop the output
        sep: string to seperate the reasoning and result
    """
    global paused
    paused = False
    reasoning = False
    temp_hotkey = keyboard.add_hotkey(hotkey,termintate_llm_output,suppress=True)
    
    for chunk in response:
        if not hasattr(chunk.choices[0].delta,"reasoning_content"):
            show_reasoning = False
        if not chunk.choices:
            continue
        if paused:
            break
        if chunk.choices[0].delta.content:
            if reasoning:
                print(sep)
                reasoning = False
            print(chunk.choices[0].delta.content, end="", flush=True)
        if show_reasoning and chunk.choices[0].delta.reasoning_content:
            if not reasoning:
                print(sep)
                reasoning = True
            print(chunk.choices[0].delta.reasoning_content, end="", flush=True)
    keyboard.clear_hotkey(temp_hotkey)
    print()